# Конфигурация системы обработки документов и RAG
embedding:
  # Настройки векторных представлений
  model_name: "thenlper/gte-small"  # Модель для эмбеддингов с HF Hub
  chunk_size: 512                   # Максимальный размер текстового фрагмента
  chunk_overlap: 100                # Перекрытие между фрагментами
  device: "cuda"                    # Устройство для вычислений (cpu/cuda/auto)

llm:
  # Настройки языковой модели
  model_name: "Qwen/Qwen2.5-14B-Instruct"  # Путь или имя модели с HF Hub
  max_new_tokens: 512               # Максимальная длина генерируемого ответа
  quantization: null                 # Квантование (4bit/8bit/null)
  system_prompt: |
    Вы опытный специалист технической поддержки, который работает в компании связанными с тендерами, твоя задача отвечать на вопросы людей. Тщательно анализируйте контекст, 
    чтобы предоставлять точные ответы на русском языке. Учитывайте:
    1. Текст может содержать опечатки или замененные слова
    2. Термины могут использовать сокращения/синонимы
    3. Ответы должны основываться ТОЛЬКО на предоставленном контексте
    После ответа приведи источники (лучше всего ссылки или название документа), из которых ты брал информацию, например база FAQ и другие документы! Все источники (другие брать нельзя): Инструкция_по_работе_с_Порталом_для_заказчика , Инструкция_по_работе_с_Порталом_для_поставщика, Инструкция_по_электронному_актированию, Регламент_информационного_взаимодействия.
    Тема указывается в самом конце, между @@тема@@, такой вывод очень важен. Тема может быть одной из следующих: тех проблемы, заказчик, исполнитель, общее. Другие темы брать нельзя. Можно брать только одну тему, формат представления только через @@theme@@! Блок с темой представляется одним словом - названием этой темы и идет это в самом конце.

processing:
  # Настройки обработки документов
  pdf_chunk_size: 1000              # Размер фрагментов для PDF
  pdf_chunk_overlap: 200            # Перекрытие фрагментов для PDF
  persist_directory: "./chroma_db"  # Директория для хранения векторной БД
  num_workers: 4                    # Количество потоков для обработки

data_sources:
  # Источники данных
  pdf_directory: "docs"        # Директория с PDF-документами
  excel_path: "docs/queries.xlsx"       # Путь к Excel-файлу с FAQ

excel_processing:
  # Настройки обработки Excel
  query_column: "Название статьи"          # Название колонки с вопросами
  answer_column: "Описание"         # Название колонки с ответами
  sheet_names:                      # Список обрабатываемых листов (null - все)
    - "Копия Статьи"
  max_rows: 1000                    # Макс. количество строк для обработки
  text_columns:                     # Колонки для объединения в текст
    - "Copy article"
  metadata_columns:                 # Колонки для включения в метаданные
    - "category"
  include_query_in_answer: true     # Включать вопрос в ответ
  chunk_size: 768                   # Размер фрагментов для Excel
  chunk_overlap: 128                # Перекрытие фрагментов для Excel